name: Arch Builder

on:
  push:
    paths:
    - 'Arch'
    - '.github/workflows/arch.yml'
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push Arch
      run: bash build.sh arch
