name: Dispatcher Build

on:
  workflow_dispatch:
    inputs:
      BUILD_TARGET:
        description: 'Build Target (arch/lite/focal,scan,all)'
        required: true
        default: 'scan'

jobs:
  focal:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.BUILD_TARGET == 'focal' }}
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: bash build.sh focal

  lite:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.BUILD_TARGET == 'lite' }}
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: bash build.sh lite

  arch:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.BUILD_TARGET == 'arch' }}
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: bash build.sh arch

  all:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.BUILD_TARGET == 'all' }}
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
          username: rzlamrr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      run: bash build.sh

  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.BUILD_TARGET == 'scan' }}
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: docker/login-action@v1.10.0
      with:
        username: rzlamrr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Scan Image
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo \
        "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -qqy docker-scan-plugin
        bash build.sh scan
      env:
        SNYK_AUTH_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Stage & Commit
      run: |
        git config --local user.email "rzlamrr.dvst@protonmail.com"
        git config --local user.name "rzlamrr"
        git add scan/
        git commit -m "ci: scan result"
    - uses: ad-m/github-push-action@v0.6.0
      with:
        directory: "scan/"
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
